services:
  - type: web
    name: anime-api
    env: node
    repo: https://github.com/itzzzme/anime-api  # <-- add this if required
    buildCommand: npm install
    startCommand: npm start
    branch: main
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 6969
